/**
 * @file main.cpp
 * @author Charlie Kushelevsky (charliekushelevsky@gmail.com)
 * @brief Entry point for the STM32U585 Uno Q peripheral-server firmware.
 * @date 2026-07-23
 *
 * Brings up the STM32Cube HAL, clock tree and generated peripherals, then
 * initialises the SPI transport and peripheral server and services
 * msgpack-rpc calls from the QRB2210 Linux side forever. Contains no
 * application/business logic; see src/platform/unoq/ for the Linux-side
 * HAL client that talks to this firmware.
 *
 * CubeMX is configured with "do not generate the main()", so this file owns
 * the entry point and the call order the generated main.c would otherwise
 * provide. The MX_*_Init() functions come from the per-peripheral headers;
 * SystemClock_Config() is generated into Core/Src/main.c with external
 * linkage but no header declaration, hence the local declaration below.
 */
#include "main.h"

#include "gpio.h"
#include "i2c.h"
#include "icache.h"
#include "peripheral_server.hpp"
#include "tim.h"
#include "transport.hpp"

/**
 * @brief Configure the clock tree for 160 MHz operation.
 *
 * Generated by STM32CubeMX into Core/Src/main.c.
 */
extern "C" void SystemClock_Config(void);

/**
 * @brief Firmware entry point.
 *
 * @return Never returns.
 */
int main()
{
    HAL_Init();
    SystemClock_Config();

    MX_GPIO_Init();
    MX_ICACHE_Init();
    MX_I2C4_Init();
    MX_TIM2_Init();

    // CubeMX generates the timer's configuration but never starts it. TIM2
    // drives sensor sampling at 55 Hz; its ISR lives in peripheral_server.cpp.
    HAL_TIM_Base_Start_IT(&htim2);

    sf_mcu::transport_init();
    sf_mcu::peripheral_server_init();

    for (;;)
    {
        sf_mcu::peripheral_server_run();
    }
}
