@startuml
start

:get lowest priority task;
repeat :get proposed task run time;
  if (clock) is (>run Time) then
   :delay exists, set delay and set proposed run time to clock (try running task now);
  else (no delay exists, set delay to 0)
  endif

  :Task Finish Time = Proposed Run Time + Task Duration;
  while (there are higher priority tasks left to check && no conflicts exist)
  if (Task Finish Time conflicts with Higher Priority Task Run Time) then
   :conflict exists;
  endif
  
  endwhile;

  if (if no conflict exists) then
   :set next task to current task;
   :update task's next run time to runTime+delay;
   :return No Error;
   stop
  endif

repeat while (get lowest priority task not yet checked )
:no tasks left to check, return error: no task found to run next;
stop
@enduml