name: Compile Firmware

on: [push]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Compile application
        id: compile
        uses: particle-iot/compile-action@v1
        with:
            particle-platform-name: 'tracker'
            device-os-version: '5.3.0'
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
            name: firmware-artifact
            path: |
                ${{ steps.compile.outputs.firmware-path }}
                ${{ steps.compile.outputs.target-path }}
  
  release:
    needs: [compile]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    if: ${{ github.ref == 'refs/heads/main' }}
    outputs:
      release: ${{ steps.release.outputs.release }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive
        ref: main

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Install Python Dependencies
      run: |
        python -m pip install -r requirements.txt
    
    - name: Set up NPM
      uses: actions/setup-node@v4
      with:
        node-version: '>=20.8.1'
    
    - name: Install plugins
      run: |
        npm install @semantic-release/exec @semantic-release/git @semantic-release/changelog -D
    
    - name: Run Semantic Release
      id: release
      env:
        GH_TOKEN : ${{ secrets.GITHUB_TOKEN }}
      run: |
        npx semantic-release@23
