name: Compile Firmware

on: [push]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Compile application
        id: compile
        uses: particle-iot/compile-action@v1
        with:
            particle-platform-name: 'tracker'
            device-os-version: '5.3.0'
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
            name: firmware-artifact
            path: |
                ${{ steps.compile.outputs.firmware-path }}
                ${{ steps.compile.outputs.target-path }}

  release:
    needs: [compile]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    if: ${{ github.ref == 'refs/heads/37-feat-semver' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive
        ref: 37-feat-semver
    
    - name: Set up NPM
      uses: actions/setup-node@v4
      with:
        node-version: '>=20.8.1'
    
    - name: Install plugins
      run: |
        npm install @semantic-release/exec -D
    
    - name: Run Semantic Release
      env:
        github-token: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npx semantic-release@23