name: Compile Firmware and Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Set up environment
      run: |
        sudo apt-get update && sudo apt-get install -y cmake build-essential        

    - name: Build and run tests
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Debug
        cd build
        make
        cd ..
        ./build/googletests | tee googletest.log

    - name: Upload test log
      uses: actions/upload-artifact@v4
      with:
        name: test_artifact
        path: |
          build/googletests
          googletest.log

  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Compile application
        id: compile
        uses: particle-iot/compile-action@v1
        with:
            particle-platform-name: 'tracker'
            device-os-version: '5.3.0'
      - name: Compile Documentation
        id: doxygen
        uses: mattnotmitt/doxygen-action@1.9.8

      - name: Check outputs
        run: |
          ls -alh doxygen/html
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
            name: firmware-artifact
            path: |
                ${{ steps.compile.outputs.firmware-path }}
                ${{ steps.compile.outputs.target-path }}
                doxygen/html
                doxygen.log

  release:
    needs: [compile, test]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    if: ${{ github.ref == 'refs/heads/main' }}
    outputs:
      release: ${{ steps.release.outputs.release }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive
        ref: main
        token: ${{ secrets.RELEASER }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Install Python Dependencies
      run: |
        python -m pip install -r requirements.txt
    
    - name: Set up NPM
      uses: actions/setup-node@v4
      with:
        node-version: '>=20.8.1'
    
    - name: Install plugins
      run: |
        npm install @semantic-release/exec @semantic-release/git @semantic-release/changelog -D
    
    - name: Run Semantic Release
      id: release
      env:
        GH_TOKEN : ${{ secrets.RELEASER }}
      run: |
        npx semantic-release@23